using System.Windows;
using System.Windows.Controls;
using System.Windows.Input;
using System.Windows.Markup;

namespace renkimsumatin.Views
{
    public partial class ScoresView : UserControl
    {
        public ScoresView()
        {
            // The InitializeComponent method is generated by the XAML compiler.
            // If you are seeing CS0103, ensure that:
            // 1. The corresponding ScoresView.xaml file exists in the same namespace and folder.
            // 2. The x:Class attribute in ScoresView.xaml matches 'renkimsumatin.Views.ScoresView'.
            // 3. The build action for ScoresView.xaml is set to 'Page'.
            // 4. The project is built successfully so that the generated code-behind file is created.

            InitializeComponent();
        }

        private void NumberValidationTextBox(object sender, TextCompositionEventArgs e)
        {
            foreach (char c in e.Text)
            {
                if (!char.IsDigit(c))
                {
                    e.Handled = true;
                    break;
                }
            }
        }
    }
}